# Generated by Django 4.2.6 on 2023-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("mac", models.TextField()),
                ("model_num", models.IntegerField()),
                ("location", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
